In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/1januarynew.csv', header=0, sep=',', usecols =['pickup_datetime','dropoff_datetime','pickup_neighborhood','dropoff_neighborhood'] )

In [3]:
df.head()

pickup_datetime     dropoff_datetime pickup_neighborhood  \
0  2016-01-01 00:00:00  2016-01-01 00:00:00   Greenwich Village   
1  2016-01-01 00:00:00  2016-01-01 00:00:00        East Village   
2  2016-01-01 00:00:00  2016-01-01 00:00:00         Boerum Hill   
3  2016-01-01 00:00:00  2016-01-01 00:00:00     Lower East Side   
4  2016-01-01 00:00:00  2016-01-01 00:00:00     Upper East Side   

  dropoff_neighborhood  
0             Gramercy  
1                  NaN  
2            Yorkville  
3                  NaN  
4              Midtown

In [4]:
number_elem = df.shape[0]
number_elem

10906858

In [5]:
df.shape[1]

4

In [6]:
#df2 = df.loc[ (df['pickup_neighborhood']!='NaN')| (df['dropoff_neighborhood']!='NaN')  ,  : ]
df.dropna(how='any', inplace=True)

In [7]:
number_elem2 = df.shape[0]
number_elem2

9755590

In [8]:
df.head()

pickup_datetime     dropoff_datetime pickup_neighborhood  \
0  2016-01-01 00:00:00  2016-01-01 00:00:00   Greenwich Village   
2  2016-01-01 00:00:00  2016-01-01 00:00:00         Boerum Hill   
4  2016-01-01 00:00:00  2016-01-01 00:00:00     Upper East Side   
5  2016-01-01 00:00:00  2016-01-01 00:18:30            Gramercy   
6  2016-01-01 00:00:00  2016-01-01 00:26:45     Lower East Side   

       dropoff_neighborhood  
0                  Gramercy  
2                 Yorkville  
4                   Midtown  
5  Astoria-Long Island City  
6           Upper West Side

In [9]:
diff = number_elem - number_elem2
diff

1151268

In [10]:
percent = (float(diff)/number_elem)*100
percent

10.55545052479825

In [11]:
neighborhoods = df['pickup_neighborhood'].value_counts()
neighborhoods

Midtown                      1696291
Upper East Side              1479416
Upper West Side               891427
Gramercy                      829680
Chelsea                       687338
Garment District              612603
Greenwich Village             480415
East Village                  369326
Murray Hill                   343472
Clinton                       313707
West Village                  238130
Lower East Side               230633
Soho                          203380
Financial District            197087
Tribeca                       167176
Central Park                  134365
Carnegie Hill                 128541
North Sutton Area             107117
Battery Park                   89912
Little Italy                   85261
Yorkville                      68208
Harlem                         47862
Morningside Heights            44602
Astoria-Long Island City       42018
Chinatown                      30729
East Harlem                    29111
Williamsburg                   28268
S

In [12]:
neighborhoods.shape

(115,)

In [13]:
neighborhoods_drop = df['dropoff_neighborhood'].value_counts()
neighborhoods_drop

Midtown                        1557450
Upper East Side                1396659
Upper West Side                 888358
Gramercy                        773653
Chelsea                         619890
Garment District                506187
Greenwich Village               389082
Murray Hill                     339864
Clinton                         338647
East Village                    334443
West Village                    221725
Financial District              212676
Lower East Side                 206549
Soho                            192828
Tribeca                         154723
Carnegie Hill                   141775
Central Park                    122717
Yorkville                       116550
Harlem                          115829
Battery Park                     94248
North Sutton Area                87938
Astoria-Long Island City         86133
Williamsburg                     72089
Morningside Heights              70743
East Harlem                      63379
Little Italy             

In [14]:
neighborhoods_drop.shape

(121,)

In [16]:
import dateutil
df['pickup_date'] = df['pickup_datetime'].apply(dateutil.parser.parse)
df['dropoff_date'] = df['dropoff_datetime'].apply(dateutil.parser.parse)

In [17]:
neighborhoods_drop.index.values

array(['Midtown', 'Upper East Side', 'Upper West Side', 'Gramercy',
       'Chelsea', 'Garment District', 'Greenwich Village', 'Murray Hill',
       'Clinton', 'East Village', 'West Village', 'Financial District',
       'Lower East Side', 'Soho', 'Tribeca', 'Carnegie Hill',
       'Central Park', 'Yorkville', 'Harlem', 'Battery Park',
       'North Sutton Area', 'Astoria-Long Island City', 'Williamsburg',
       'Morningside Heights', 'East Harlem', 'Little Italy', 'Fort Green',
       'Washington Heights', 'Sunny Side', 'Bedford-Stuyvesant',
       'Hamilton Heights', 'Park Slope', 'Chinatown', 'Downtown',
       'Bushwick', 'Jackson Heights', 'Carroll Gardens', 'Boerum Hill',
       'Woodside', 'Forest Hills', 'Mott Haven', 'Inwood', 'Cobble Hill',
       'South Bronx', 'Bay Ridge', 'Ridgewood', 'Borough Park',
       'Mapleton-Flatlands', 'Sunset Park', 'Greenwood', 'High Bridge',
       'Gravesend-Sheepshead Bay', 'Nkew Gardens', 'Maspeth', 'Riverdale',
       'Utopia', 'Middle Vi

In [18]:
len(neighborhoods_drop.index.tolist())

121

In [56]:
x = df['pickup_neighborhood'].unique().tolist()
x.sort()
x

['Annandale',
 'Ardon Heights',
 'Astoria-Long Island City',
 'Auburndale',
 'Battery Park',
 'Bay Ridge',
 'Baychester',
 'Bedford Park',
 'Bedford-Stuyvesant',
 'Bensonhurst',
 'Bloomfield-Chelsea-Travis',
 'Boerum Hill',
 'Borough Park',
 'Brownsville',
 'Bushwick',
 'Canarsie',
 'Carnegie Hill',
 'Carroll Gardens',
 'Central Park',
 'Chelsea',
 'Chinatown',
 'City Island',
 'Clearview',
 'Clifton',
 'Clinton',
 'Cobble Hill',
 'Corona',
 'Country Club',
 'Douglastown-Little Neck',
 'Downtown',
 'Dyker Heights',
 'East Brooklyn',
 'East Harlem',
 'East Village',
 'Eastchester',
 'Ettingville',
 'Financial District',
 'Flatbush',
 'Flushing',
 'Fordham',
 'Forest Hills',
 'Fort Green',
 'Garment District',
 'Glendale',
 'Gramercy',
 'Gravesend-Sheepshead Bay',
 'Greenwich Village',
 'Greenwood',
 'Hamilton Heights',
 'Harlem',
 'High Bridge',
 'Howland Hook',
 'Huguenot',
 'Hunts Point',
 'Inwood',
 'Jackson Heights',
 'Jamaica',
 'Kings Bridge',
 'Laurelton',
 'Little Italy',
 'Lowe

In [21]:
import numpy as np

#Here we just get the total amount of trips from neighborhood to neighborhood

def fromNeighborhoodsFeatures(data, column_neighborhoods_from, column_neighborhoods_to):
    #Get a set of the Neighborhoods where people were pickedup
    Neighborhoods = data[column_neighborhoods_from].unique().tolist()
    Neighborhoods = set(Neighborhoods)
    #Update the set with the Neighborhoods where people were dropoff
    Neighborhoods.update(  data[column_neighborhoods_to].unique().tolist() )
    
    # Convert the set to a list so we can use the indexes for the np.array
    Neighborhoods = list(Neighborhoods)
    Neighborhoods.sort()
    print("Value of column_neighborhoods_from: %s"%(column_neighborhoods_from))
    print("Number of neighborhoods: %d"%(len(Neighborhoods)))
    array = np.zeros( ( len(Neighborhoods),len(Neighborhoods) ) )
    
    iter_ = data.iterrows()
    # iterrows() give (Index, Series) pairs where the Series are the rows
    for e in iter_:
        origin = e[1][column_neighborhoods_from]
        #print("Pickup: "+origin)
        destiny = e[1][column_neighborhoods_to]
        #print("Dropoff: "+destiny)
        origin_index = Neighborhoods.index(origin)
        destiny_index = Neighborhoods.index(destiny)
        
        freq =  array[origin_index,destiny_index]          
        freq +=1
        #Line below is unnecesarry???????????
        array[origin_index,destiny_index] = freq
    
    return array
    

In [22]:
df.head()

pickup_datetime     dropoff_datetime pickup_neighborhood  \
0  2016-01-01 00:00:00  2016-01-01 00:00:00   Greenwich Village   
2  2016-01-01 00:00:00  2016-01-01 00:00:00         Boerum Hill   
4  2016-01-01 00:00:00  2016-01-01 00:00:00     Upper East Side   
5  2016-01-01 00:00:00  2016-01-01 00:18:30            Gramercy   
6  2016-01-01 00:00:00  2016-01-01 00:26:45     Lower East Side   

       dropoff_neighborhood pickup_date        dropoff_date  
0                  Gramercy  2016-01-01 2016-01-01 00:00:00  
2                 Yorkville  2016-01-01 2016-01-01 00:00:00  
4                   Midtown  2016-01-01 2016-01-01 00:00:00  
5  Astoria-Long Island City  2016-01-01 2016-01-01 00:18:30  
6           Upper West Side  2016-01-01 2016-01-01 00:26:45

In [42]:
df['pickup_hour'] = df['pickup_date'].dt.hour
df.head()
#df.loc[0, 'pickup_date'].hour

pickup_datetime     dropoff_datetime pickup_neighborhood  \
0  2016-01-01 00:00:00  2016-01-01 00:00:00   Greenwich Village   
2  2016-01-01 00:00:00  2016-01-01 00:00:00         Boerum Hill   
4  2016-01-01 00:00:00  2016-01-01 00:00:00     Upper East Side   
5  2016-01-01 00:00:00  2016-01-01 00:18:30            Gramercy   
6  2016-01-01 00:00:00  2016-01-01 00:26:45     Lower East Side   

       dropoff_neighborhood pickup_date        dropoff_date  pickup_hour  
0                  Gramercy  2016-01-01 2016-01-01 00:00:00            0  
2                 Yorkville  2016-01-01 2016-01-01 00:00:00            0  
4                   Midtown  2016-01-01 2016-01-01 00:00:00            0  
5  Astoria-Long Island City  2016-01-01 2016-01-01 00:18:30            0  
6           Upper West Side  2016-01-01 2016-01-01 00:26:45            0

In [47]:
#Here we just get the total amount of trips from neighborhood to neighborhood
# temp_bands is a list of the upper-limit of each temporal band
# example: if our temporal bands are [0-6), [6-12), [12-18), [18-24)
# the list will be [ 6 , 12 , 18, 24 ] ; the validation being
# for i in temp_bands:
#     if time < i:
#        return temp_bands.index(i)

def fromNeighborhoodsFeaturesHour(data, column_neighborhoods_from, column_neighborhoods_to, time_column ,temp_bands):
    #Get a set of the Neighborhoods where people were pickedup
    Neighborhoods = data[column_neighborhoods_from].unique().tolist()
    Neighborhoods = set(Neighborhoods)
    #Update the set with the Neighborhoods where people were dropoff
    Neighborhoods.update(  data[column_neighborhoods_to].unique().tolist() )
    
    # Convert the set to a list so we can use the indexes for the np.array
    Neighborhoods = list(Neighborhoods)
    Neighborhoods.sort()
    print("Value of column_neighborhoods_from: %s"%(column_neighborhoods_from))
    print("Number of neighborhoods: %d"%(len(Neighborhoods)))
    
    #Initialize the array
    
    array = np.zeros( ( len(Neighborhoods),len(Neighborhoods), len(temp_bands) ) )
    
    iter_ = data.iterrows()
    # iterrows() give (Index, Series) pairs where the Series are the rows
    for e in iter_:
        origin = e[1][column_neighborhoods_from]
        #print("Pickup: "+origin)
        destiny = e[1][column_neighborhoods_to]
        #print("Dropoff: "+destiny)
        
        origin_index = Neighborhoods.index(origin)
        destiny_index = Neighborhoods.index(destiny)
        #get the time        
        hour = e[1][time_column]
        #get the index of the temporal bands
        hour_index = 0
        for i in temp_bands:
            if hour < i:
                hour_index = temp_bands.index(i)
                break
        
        freq =  array[origin_index,destiny_index, hour_index]          
        freq +=1
        #Line below is unnecesarry???????????
        array[origin_index,destiny_index, hour_index] = freq
    
    return array

In [49]:
temporal_band = [ 6 , 12 , 18, 24 ]
features = fromNeighborhoodsFeaturesHour(df, 'pickup_neighborhood', 'dropoff_neighborhood','pickup_hour' ,temporal_band)

Value of column_neighborhoods_from: pickup_neighborhood
Number of neighborhoods: 121


In [68]:
fea2 = features[0:2 ,0:2 ,:]
fea2.shape
# tenemos (x,y,z) y queremos un array de la forma (x, y*z)

(2, 2, 4)

In [72]:
fea2

array([[[ 2.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  1.]]])

In [58]:
features.shape

(121, 121, 4)

In [69]:
fea3  = fea2.reshape(2,8)
fea3

array([[ 2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.]])

In [73]:
shape = features.shape
features_2D = features.reshape(shape[0], shape[1]*shape[2]  )

In [59]:
from sklearn.cluster import KMeans

In [78]:
kmeans = KMeans(n_clusters=3, random_state=0).fit(features_2D)
kmeans.labels_

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2,
       2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0,
       2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2], dtype=int32)

In [79]:
kmeans.labels_.size

121

In [80]:
kmeans.cluster_centers_

array([[  1.42857143e-01,   0.00000000e+00,   0.00000000e+00, ...,
          1.06371429e+03,   1.05157143e+03,   1.37742857e+03],
       [  1.00000000e+00,   0.00000000e+00,   5.00000000e-01, ...,
          7.69550000e+03,   8.33350000e+03,   9.10250000e+03],
       [  7.14285714e-02,   0.00000000e+00,   1.90819582e-17, ...,
          8.33750000e+01,   7.37321429e+01,   6.78928571e+01]])

In [81]:
features[features>0].size

17783